version: "3.9"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  passenger-service:
    build: ./passenger-service
    container_name: passenger-service
    ports:
      - "8081:8080"
    depends_on:
      - kafka
      - mongo

  ticketing-service:
    build: ./ticketing-service
    container_name: ticketing-service
    ports:
      - "8082:8080"
    depends_on:
      - kafka
      - mongo

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8083:8080"
    depends_on:
      - kafka
      - mongo

  validator-service:
    build: ./validator-service
    container_name: validator-service
    ports:
      - "8084:8080"
    depends_on:
      - kafka
      - mongo

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8085:8080"
    depends_on:
      - kafka
      - mongo

  admin-service:
    build: ./admin-service
    container_name: admin-service
    ports:
      - "8086:8080"
    depends_on:
      - kafka
      - mongo

volumes:
  mongo_data:
